"""initial schema

Revision ID: bf063dd4332d
Revises: 
Create Date: 2026-09-20 23:13:23.815747

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'bf063dd4332d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
